### ISSUE TITLE
Various updates

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/smtp#1]
Hi @biolithic !

We needed this module for backdropcms.org today so I went ahead and finished the port. I think I found the problem that was causing trouble for the other modules, so if you want to try those again it might be a good time.

I've added myself as a maintainer for this project so I can make an official release, but left your name in the credits section. Let me know if you want to be my co-maintainer and I'll add you there too.

Thanks for all the good work on getting this started :) You made my job easy today ;)

**Comment by biolithic** [comment]
I don't care if you take maintainer, I just wanted to push the community
forward at the time I started it (whenever that was).
Went backwards and then made progress (maybe) on trying to make layouts
over the holiday so will try to publish this week and get back to modules
this month.

**Comment by jenlampton** [comment]
Fantastic :) Thanks for all your effort!
(closing this issue)
