### ISSUE TITLE
The submitted from address (=?UTF-8.....) is not valid

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/smtp#14]
Is it possible to adapt the solution from https://www.drupal.org/project/smtp/issues/1790436 on this module? I'm getting the same issue using smtp adresses like webmaster@my-domain.tld.

**Comment by indigoxela** [comment]
> Is it possible to adapt the solution from... (Drupal)

In theory it's easy, in practice... Adding the fix is no problem, but the the functional tests really need more update work, than I'm willing to do here as non-maintainer.

**Comment by indigoxela** [comment]
Anyway, a PR (patch) is available.

**Comment by djzwerg** [comment]
Thanks @indigoxela but this doesn't solve the issue.

**Comment by indigoxela** [comment]
> this doesn't solve the issue.

Which version are you using? I can see that the latest release for Backdrop was 2018, but in 2019 some important updates were made.

**Comment by indigoxela** [comment]
I've updated the PR to also include the fixes from https://www.drupal.org/project/smtp/issues/2753115

@djzwerg if that doesn't fix it for you, could you please post the full error message?

**Comment by jenlampton** [comment]
I've merged the PR since the changes appear safe, but if they do not fix your problem @djzwerg please re-open the issue and we can try something else.

**Comment by djzwerg** [comment]
@jenlampton thanks a lot. I will test it later.
