### ISSUE TITLE
each() is undefined in PHP 8.0

### ISSUE THREAD

**Issue by tkcent** [backdrop-contrib/smtp#16]
Call to undefined function each() in SMTP->Data() (line 400 of modules/smtp/includes/smtp.transport.inc).

Drupal issue: https://www.drupal.org/project/smtp/issues/2946667

**Comment by robertgarrigos** [comment]
I confirm the pr associated to this issue solves the problem

**Comment by klonos** [comment]
@jenlampton ping 👋🏼 

We have hit this issue when trying to switch the forum site to be using php8.
