### ISSUE TITLE
"Feature parody" ...LOL!

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/smtp#2]
![backdrop-contrib-spam-feature_parody](https://cloud.githubusercontent.com/assets/2423362/12209726/1d1e299a-b6a9-11e5-8901-4f0459af7064.png)

Fixed that for you, but really LOL :laughing:

**Comment by klonos** [comment]
...just filed this issue in case it was intentional, in which case just let me know and I'll revert changes.

**Comment by zhongyimi** [comment]
cannot send any email on sharing hosting

**Comment by klonos** [comment]
@zhongyimi can you please file a separate issue for that?

**Comment by klonos** [comment]
I believe this is fixed @jenlampton
