### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by samgreco** [backdrop-contrib/smtp#26]
When trying to uninstall I get:  Call to a member function get() on null 

Website can't seem to authenticate to Office365, so I am trying to uninstall and reinstall clean.  This was an upgrade from Drupal 7.

SMTP Version 1.x-1.7.1

**Comment by indigoxela** [comment]
Confirmed, the problem is a non-existent config variable here:
https://github.com/backdrop-contrib/smtp/blob/1.x-1.x/smtp.install#L47

```
$config = config('smtp.settings');
```

**Comment by bugfolder** [comment]
PR submitted that fixes it.

**Comment by indigoxela** [comment]
@bugfolder wow, that was fast!

I can confirm, that the patch fixes the problem. :+1:

**Comment by yorkshire-pudding** [comment]
I can also confirm that this fixes the issue. @jenlampton please can you merge and release?

**Comment by herbdool** [comment]
Merged on behalf of the @backdrop-contrib/bug-squad
