### ISSUE TITLE
Error: Call to undefined function get_magic_quotes_runtime()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/smtp#27]
This error started appearing my dblog:

Error: Call to undefined function get_magic_quotes_runtime() in PHPMailer->EncodeFile() (line 1445 of /mysite/modules/contrib/smtp/includes/smtp.phpmailer.inc).

That's a PHP function, but PHP says [it's now removed in PHP 8.0+](https://www.php.net/manual/en/function.get-magic-quotes-runtime) (and I just upgraded the site from PHP 7.4 to 8.1).

Can we update this module for PHP 8.1 compatibility?

**Comment by indigoxela** [comment]
Here's a [PR](https://github.com/backdrop-contrib/smtp/pull/33) to fix that.

**Comment by herbdool** [comment]
Since backdrop supports from PHP 5.6 I think we might want to leave it in and add a check for less than 8.0 instead.

**Comment by indigoxela** [comment]
> Since backdrop supports from PHP 5.6 I think we might want to leave it in...

Not necessarily. It's not only about [get_magic_quotes_runtime()](http://php.adamharvey.name/manual/en/function.get-magic-quotes-runtime.php), which was deprecated in 7.4.0, and removed as of PHP 8.0. It's also about [set_magic_quotes_runtime()](http://php.adamharvey.name/manual/en/function.set-magic-quotes-runtime.php), which was deprecated 5.3.0, and removed as of PHP 7.0.0.

And in general it's discouraged to rely on magic quotes.

In D7 this has been [removed as well](https://www.drupal.org/project/smtp/issues/3009090).

Seems like the ini directives for magic_quotes have been removed in PHP 5.4 or so, but I can't find an official document for that, as this is "dead" for so long now. :wink: This ini setting doesn't have any effect for a while.

**Comment by yorkshire-pudding** [comment]
I support removing these.  Looking at the PR, removing these doesn't seem to stop any functionality, so even if someone on PHP 5.6 updates the SMTP module (very unlikely - look at telemetry for Backdrop and usage for Backdrop and SMTP), they will still be able to use the module.

FA: @jenlampton

**Comment by indigoxela** [comment]
Given, that this PR is now several months old, this issue may qualify for @backdrop-contrib/bug-squad interaction? :wink:

**Comment by herbdool** [comment]
We need some testing before bug squad can do anything.

**Comment by yorkshire-pudding** [comment]
I'll do some testing with different versions of PHP tomorrow

**Comment by yorkshire-pudding** [comment]
@herbdool @indigoxela - I have tested this PR on PHP versions: 5.6, 7.4, 8.2 and 8.3
All with logs and messages set to max
All successfully sent the emails with nothing but a success message in the logs.

**Comment by herbdool** [comment]
Thorough testing @yorkshire-pudding thanks! I think we can merge it now.
