### ISSUE TITLE
Config system.mail data structure

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/smtp#3]
I am a bit puzzled because in this module in smtp.install there is
`
config_set('system.mail', 'mail_system', array('default-system' => 'SmtpMailSystem'));
`
whereas elsewhere, such as in Simpletest, there is
`
config_set('system.mail', 'default-system', 'TestingMailSystem');
`

My understanding of core's mail system (mail.inc) is that the latter is right. This is important to me because of work I am doing on Views Send and Mimemail, and the new module Simple Mailsystem that I have just produced in order to avoid the complexities of the ported module Mailsystem.

Also see https://api.backdropcms.org/node/28531

**Comment by jenlampton** [comment]
Yes, you are correct. I think I was looking at this when I updated the wrong thing for smtp:

``` php
$config->setData(update_variable_get('mail_system', array('default-system' => 'DefaultMailSystem')));
```
