### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/smtp#34]
Some issues have been fixed in D7, but there's more.

This issue here combines several PHP 8 compat tasks.

**Comment by indigoxela** [comment]
PHPStan finds a lot more to nag, but here we address the "undefined property" issues:

- Access to an undefined property PHPMailer::$is_html.
- Access to an undefined property PHPMailer::$DKIM_passphrase
- Access to an undefined property PHPMailerOAuth::$AuthType
- Access to an undefined property PHPMailerOAuth::$SMTPOptions

They're possible not used often, but finding these violations is the benefit of static analysis. :wink:

**Comment by herbdool** [comment]
The PR looks good. RTBC.

I'll add that it also removes reference to safe_mode which was removed in PHP 5.4.

**Comment by yorkshire-pudding** [comment]
I also confirm this works.  Please can this be merged and released @jenlampton

**Comment by yorkshire-pudding** [comment]
@jenlampton - I've had this patch working for some time now and it definitely works.

**Comment by herbdool** [comment]
Merged on the behalf of the @backdrop-contrib/bug-squad
