### ISSUE TITLE
Deprecated function variable_get()

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/smtp#38]
This is appearing in the log if set to log deprecations errors. The category is 'bootstrap'

> The function PHPMailer->__construct() (smtp.phpmailer.inc:347) called deprecated function variable_get(). It will be removed in the next major release of Backdrop.

**Comment by herbdool** [comment]
@yorkshire-pudding can you confirm the PR fixes this?

**Comment by yorkshire-pudding** [comment]
Hi @herbdool - Tested before and after the patch and confirm that this PR fixes this.
Thank you.
